title = "The Naive Bayesian"
baseURL = "https://the-naive-bayesian.github.io"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "A blog by Chris Emerson"
  facebook = ""
  twitter = "https://twitter.com/Naiv3Bayesian"
  instagram = ""
  youtube = ""
  github = "https://github.com/The-Naive-Bayesian"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/chris-emerson/"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 2
